# Trigger builds only when a commit gets
# merged to master and relates to the path
# cronjob/*.
# Batch multiple builds.
# Do not trigger PR validation builds.
trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    include:
    - cronjob/*
pr: none

resources:
- repo: self

variables:
  commitId: '$(Build.SourceVersion)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build image and push it to DockerHub
      inputs:
        containerRegistry: 'teamdigitalesa'
        repository: 'teamdigitale/anpr-dashboard-cronjob'
        command: 'buildAndPush'
        dockerfile: '$(Build.SourcesDirectory)/cronjob/Dockerfile'
        tags: |
          $(commitId)
          latest
