# Trigger builds only when a commit gets
# merged to master. Do not trigger PR
# validation builds.
# Exclude the path cronjob/*
# Batch builds if multiple exist.
trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    exclude:
    - cronjob/*
pr: none

resources:
- repo: self

variables:
  commitId: '$(Build.SourceVersion)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build image and push it to DockerHub
      inputs:
        containerRegistry: 'teamdigitalesa'
        repository: 'teamdigitale/anpr-dashboard-server'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(commitId)
          latest
