version: '3.0'

services:
  server:
    build: .
    user: "$UID"
    volumes:
    - vault:/srv/anpr/vault
    - db:/srv/anpr/db
    - cache:/var/cache/dashboard_scripts
    entrypoint:
    - "/srv/anpr/server/dashboard"
    - "--http-listen-on=[::]:8080"
    # Config file
    - "--config-file=/srv/anpr/vault/config.yaml"
    # Credentials
    - "--cookie-creds=/srv/anpr/vault/cookie-creds.json"
    - "--email-creds=/srv/anpr/vault/email-creds.yaml"
    - "--oauth-creds=/srv/anpr/vault/oauth-creds.yaml"
    # Other files embedded in the Docker image
    - "--web-templates=/srv/anpr/server/templates/"
    - "--email-templates=/srv/anpr/server/emails/"
    - "--static-content=/srv/anpr/server/static/"
