version: '3.0'

services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env.example
    user: "$UID"
    volumes:
      - ../cache:/var/cache/dashboard_scripts
